[editor]
# how many lines between the cursor and the edge of the editor before scorlling begins
# the default 5 means once your cursor gets to 5 lines before the top or bottom of the screen scrolling will begin
# this means your cursor would not reach the top/bottom of the screen until you reach the start/end of the file
scroll_buffer = 5
