[theme]
gutter_bg = "#000000"
gutter_fg = "#FFFFFF"
status_bg = "#FFFFFF"
status_fg = "#000000"
text_fg = "#FFFFFF"
variable_fg = "#89B4FA"
keyword_fg = "#CBA6F7"
type_fg = "#F9E2AF"
string_fg = "#A6E3A1"
comment_fg = "#6C7086"
number_fg = "#FAB387"
function_fg = "#89DCEB"
