[editor]
# how many lines between the cursor and the edge of the editor before scrolling begins
scroll_buffer = 5
# relative or normal
line_numbers = "relative"
# default, catppuccin, ocean, amber, forest, rose, slate, paper, violet
# Custom themes can be added by putting placing a file in zag/themes/FILENAME.toml
# FILENAME and the theme name below must be the same
# see ./examples/themes/red.toml for an example custom theme
theme = "default"
